### ISSUE TITLE
No module named parse

### ISSUE THREAD

**Issue by az09** [gis-lab-info/website#14]
При попытке развернуть сайт локально с помощью [обновленного](https://github.com/gis-lab-info/website/commit/cbbaa5a6c786d90f1216b4f2a6ba5530a7ccefeb) скрипта получил ошибку
![image](https://github.com/gis-lab-info/website/assets/1209966/e8edb12f-f293-4c31-9a8f-7572f89b4010)
```
$ ./ssi-server --skip-missing
Traceback (most recent call last):
  File "/home/ant/Documents/gis-lab/website/env/lib/python2.7/site.py", line 190, in <module>
    main()
  File "/home/ant/Documents/gis-lab/website/env/lib/python2.7/site.py", line 14, in main
    sys.real_prefix = sys.base_prefix = config["base-prefix"]
KeyError: 'base-prefix'
```
Откуда 2-ой то?! Надо как-то переключиться на 3-й интерпретатор? @drnextgis

**Comment by drnextgis** [comment]
Нужно использовать Python3. В инструкции написано как создать виртуальное окружение для Py3.
